name: skripsi_mulia_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  http: ^1.2.1
  get_it: ^7.1.3
  go_router: ^14.0.2
  google_fonts: ^6.2.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  build_runner: ^2.4.8
flutter:
  assets:
    - assets/images/logo_um.png
  uses-material-design: true
